# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: TBD
name: scaleway
version: 1.2.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
  - fsodogandji (https://github.com/fsodogandji)
description: Scaleway Ansible Collection.
license_file: LICENSE
tags:
  - scaleway
  - cloud
  - secret
repository: https://github.com/fsodogandji/community.scaleway
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/fsodogandji/community.scaleway
issues: https://github.com/fsodogandji/community.scaleway/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .DS_Store
  - "*.tar.gz"